// ./general
export { default as SectionCorporateCourse } from '@/components/sections/general/SectionCorporateCourse'
export { default as SectionGeneralTeachersAlt } from '@/components/sections/general/SectionGeneralTeachersAlt'
export { default as SectionHowProcessGoesAlt } from '@/components/sections/general/SectionHowProcessGoesAlt'
export { default as SectionInternationalExperts } from '@/components/sections/general/SectionInternationalExperts'
export { default as SectionMoreRelevant } from '@/components/sections/general/SectionMoreRelevant'
export { default as SectionOurGraduates } from '@/components/sections/general/SectionOurGraduates'
export { default as SectionRelevantContentOnly } from '@/components/sections/general/SectionRelevantContentOnly'
export { default as SectionReviewsAlt } from '@/components/sections/general/SectionReviewsAlt'
export { default as SectionTrustedByAlt } from '@/components/sections/general/SectionTrustedByAlt'
export { default as SectionYourDiplomasAlt } from '@/components/sections/general/SectionYourDiplomasAlt'

// ./payment
export { default as SectionPaymentTinkoff } from '@/components/sections/payment/SectionPaymentTinkoff'

// ./
export { default as About } from '@/components/sections/all/About'
export { default as ActiveLicenses } from '@/components/sections/all/ActiveLicenses'
export { default as BriefProgramContents } from '@/components/sections/all/BriefProgramContents'
export { default as CheckLicense } from '@/components/sections/all/CheckLicense'
export { default as ContactForm } from '@/components/sections/all/ContactForm'
export { default as Contacts } from '@/components/sections/all/Contacts'
export { default as Cta } from '@/components/sections/all/Cta'
export { default as Desc } from '@/components/sections/all/Desc'
export { default as Diplomas } from '@/components/sections/all/Diplomas'
export { default as Faq } from '@/components/sections/all/Faq'
export { default as FilterSearch } from '@/components/sections/all/FilterSearch'
export { default as ForWhom } from '@/components/sections/all/ForWhom'
export { default as FullProgram } from '@/components/sections/all/FullProgram'
export { default as HelpWithEmployment } from '@/components/sections/all/HelpWithEmployment'
export { default as Hero } from '@/components/sections/all/Hero'
export { default as HeroProgram } from '@/components/sections/all/HeroProgram'
export { default as HeroPrograms } from '@/components/sections/all/HeroPrograms'
export { default as HowProcessGoes } from '@/components/sections/all/HowProcessGoes'
export { default as LegalDocs } from '@/components/sections/all/LegalDocs'
export { default as LegalInfo } from '@/components/sections/all/LegalInfo'
export { default as MeetYourTeachers } from '@/components/sections/all/MeetYourTeachers'
export { default as PaymentBtns } from '@/components/sections/all/PaymentBtns'
export { default as PaymentDebitCard } from '@/components/sections/all/PaymentDebitCard'
export { default as PaymentInfo } from '@/components/sections/all/PaymentInfo'
export { default as Programs } from '@/components/sections/all/Programs'
export { default as Reviews } from '@/components/sections/all/Reviews'
export { default as SectionStudyFields } from '@/components/sections/all/SectionStudyFields'
export { default as StudyCost } from '@/components/sections/all/StudyCost'
export { default as Teachers } from '@/components/sections/all/Teachers'
export { default as TrustedBy } from '@/components/sections/all/TrustedBy'
export { default as Webinars } from '@/components/sections/all/Webinars'
export { default as WebinarsAlt } from '@/components/sections/all/WebinarsAlt'
export { default as WhatYouWillLearn } from '@/components/sections/all/WhatYouWillLearn'
export { default as WhyBother } from '@/components/sections/all/WhyBother'
export { default as YourDiploma } from '@/components/sections/all/YourDiploma'
export { default as YourFutureJob } from '@/components/sections/all/YourFutureJob'
export { default as YourResume } from '@/components/sections/all/YourResume'
